### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by wubinbai** [lRomul/argus-freesound#3]
As of June 15., 2020.

After installing Docker and NVIDIA/Docker, after running  python make_folds.py

When running     python train_folds.py --experiment corr_noisy_008

ModuleNotFoundError: No module named 'numba.decorators'

Solution:
(refer to https://github.com/deezer/spleeter/issues/419)
pip install numba==0.43.0
pip install llvmlite==0.32.1

**Comment by wubinbai** [comment]
how may I add this to the Dockerfile? and Makefile? Possibly? Thanks!~!

**Comment by lRomul** [comment]
Added package versions to Dockerfile. Thank you!
