### ISSUE TITLE
val_step() takes 2 positional arguments but 3 were given when training

### ISSUE THREAD

**Issue by Ryuk17** [lRomul/argus-freesound#7]
I run the train_fold.py and meet the following problem when training.
`val_step() takes 2 positional arguments but 3 were given `  
I have no idea what leads to this problem. In each step, we get a tri-tuple from the dataloader, namely image, target, noisy.  But the noisy is a zero tensor, how to feeds the noisy tenor to model ? Dose the noisy tensor result in the problem?

**Comment by Ryuk17** [comment]
I locate the problem with step debug
![image](https://user-images.githubusercontent.com/22525811/111743036-098af000-88c4-11eb-9146-9c7247b0480c.png)
Everything seems be OK, but it reports that val_step() takes 2 positional arguments but 3 were given
![image](https://user-images.githubusercontent.com/22525811/111743103-258e9180-88c4-11eb-9259-a4e56b45a3bd.png)

**Comment by lRomul** [comment]
Hi! Thank you for reporting the problem and additional information. Today I will try to reproduce the error.

**Comment by lRomul** [comment]
I successfully run training via instructions in the readme. 
I need more information. What environment do you have? Do you use Docker or your setup up? If yours which versions of python and packages do you use?

**Comment by Ryuk17** [comment]
> I successfully run training via instructions in the readme.
> I need more information. What environment do you have? Do you use Docker or your setup up? If yours which versions of python and packages do you use?

Thanks for your reply. I just found that I install the newest pytorch-argus but I didn't notice that you updated the argus_models.py several month ago. After changing the code in argus_models.py, it run successfully, Thanks again.

**Comment by lRomul** [comment]
Great, glad the issue is solved!
